# Default values for gateway-helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/choerodon-framework/gateway-helper
  pullPolicy: Always

preJob:
  timeout: 300
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.5.6
  preConfig:
    enable: true
    configFile: application.yml
    datasource:
      url: jdbc:mysql://localhost:3306/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: username
      password: password

deployment:
  managementPort: 9181

env:
  open:
     SPRING_CLOUD_CONFIG_ENABLED: true
     SPRING_CLOUD_CONFIG_URI: http://localhost:8010
     SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1/iam_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
     SPRING_DATASOURCE_USERNAME: username
     SPRING_DATASOURCE_PASSWORD: password
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://register-server.io-choerodon:8000/eureka/
     SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092
     SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.zookeeper.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.zookeeper.svc.cluster.local:2181
     SPRING_CACHE_MULTI_L1_ENABLED: true
     SPRING_CACHE_MULTI_L2_ENABLED: false
     SPRING_REDIS_HOST: localhost
     SPRING_REDIS_PORT: 6379
     SPRING_REDIS_DATABASE: 4


     SKYWALKING_ENABLED: true
     #skywalking代理jar包，添加则开启skywalking，删除则关闭
     SKYWALKING_JAVAAGENT: /agent/skywalking-agent.jar
     #skywalking ui显示的应用名称，默认为服务名
     SKYWALKING_AGENTCOLLECTOR_BACKEND_SERVICE_APPLICATION_CODE: gateway-helper
     #oap服务地址和端口
     SKYWALKING_COLLECTOR_BACKEND_SERVICE: oap.skywalking:11800
     #采样率，每三秒采样次数，-1表示100%采样率
     SKYWALKING_AGENT_SAMPLE_N_PER_3_SECS: -1
#    #此参数用以表明跨进程链路之中的header；不同的namespace在一次跨进程链路中会导致链路中断
#    SKYWALKING_AGENT_NAMESPACE: default-namespace
#    #与Collector进行通信的token，需要与collector设置的一样
#    SKYWALKING_AGENT_AUTHENTICATION: xxxx
#    #每个Segment中最多有多少个Span
#    SKYWALKING_AGENT_SPAN_LIMIT_PER_SEGMENT:
#    #需要忽略的调用
#    SKYWALKING_AGENT_IGNORE_SUFFIX:
#    #是否保存增强后的字节码文件
#    SKYWALKING_AGENT_IS_OPEN_DEBUGGING_CLASS:
service:
  enable: false
  type: ClusterIP
  port: 9180
  name: gateway-helper

metrics:
  path: /prometheus
  label: spring-boot

logs:
  parser: spring-boot

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 3Gi
  requests:
    # cpu: 100m
    memory: 2Gi